server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://postgres-progress:5432/sandbox_progress
    username: postgres
    password: adedeji1127
  jpa:
    hibernate:
      ddl-auto: update