services:
  discovery-service:
    build: { context: ., args: { SERVICE_NAME: discovery-service } }
    container_name: discovery-service
    ports: ["8761:8761"]
    networks: [sandbox-net]

  config-server:
    build: { context: ., args: { SERVICE_NAME: config-server } }
    container_name: config-server
    ports: ["8888:8888"]
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on: [discovery-service]
    networks: [sandbox-net]

  auth-service:
    build: { context: ., args: { SERVICE_NAME: auth-service } }
    container_name: auth-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-auth:5432/sandbox_auth
      - SPRING_DATASOURCE_PASSWORD=adedeji1127
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on: [discovery-service, config-server, postgres-auth]
    networks: [sandbox-net]

  container-sim-service:
    build: { context: ., args: { SERVICE_NAME: container-sim-service } }
    container_name: container-sim-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-containers:5432/sandbox_containers
      - SPRING_DATASOURCE_PASSWORD=adedeji1127
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on: [discovery-service, config-server, postgres-containers]
    networks: [sandbox-net]

  manifest-service:
    build: { context: ., args: { SERVICE_NAME: manifest-service } }
    container_name: manifest-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-manifest:5432/sandbox_manifest
      - SPRING_DATASOURCE_PASSWORD=adedeji1127
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on: [discovery-service, config-server, postgres-manifest]
    networks: [sandbox-net]

  progress-service:
    build: { context: ., args: { SERVICE_NAME: progress-service } }
    container_name: progress-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-progress:5432/sandbox_progress
      - SPRING_DATASOURCE_PASSWORD=adedeji1127
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on: [discovery-service, config-server, postgres-progress]
    networks: [sandbox-net]

  loadbalancer-sim-service:
    build: { context: ., args: { SERVICE_NAME: loadbalancer-sim-service } }
    container_name: loadbalancer-sim-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on: [discovery-service, config-server]
    networks: [sandbox-net]

  api-gateway:
    build: { context: ., args: { SERVICE_NAME: api-gateway } }
    container_name: api-gateway
    ports: ["8080:8080"]
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on: [discovery-service, config-server]
    networks: [sandbox-net]

  # --- DATABASES ---
  postgres-auth:
    image: postgres:15-alpine
    container_name: postgres-auth
    environment: { POSTGRES_DB: sandbox_auth, POSTGRES_USER: postgres, POSTGRES_PASSWORD: adedeji1127 }
    volumes: ["./data/auth:/var/lib/postgresql/data"]
    networks: [sandbox-net]

  postgres-containers:
    image: postgres:15-alpine
    container_name: postgres-containers
    environment: { POSTGRES_DB: sandbox_containers, POSTGRES_USER: postgres, POSTGRES_PASSWORD: adedeji1127 }
    volumes: ["./data/containers:/var/lib/postgresql/data"]
    networks: [sandbox-net]

  postgres-progress:
    image: postgres:15-alpine
    container_name: postgres-progress
    environment: { POSTGRES_DB: sandbox_progress, POSTGRES_USER: postgres, POSTGRES_PASSWORD: adedeji1127 }
    volumes: ["./data/progress:/var/lib/postgresql/data"]
    networks: [sandbox-net]

  postgres-manifest:
    image: postgres:15-alpine
    container_name: postgres-manifest
    environment: { POSTGRES_DB: sandbox_manifest, POSTGRES_USER: postgres, POSTGRES_PASSWORD: adedeji1127 }
    volumes: ["./data/manifest:/var/lib/postgresql/data"]
    networks: [sandbox-net]


  frontend-ui:
    build:
      context: ./devops-cloundsandbox-frontend
      dockerfile: Dockerfile
    container_name: frontend-ui
    ports:
      - "5173:80"
    networks:
      - sandbox-net
    depends_on:
      - api-gateway
      -
networks:
  sandbox-net:
    driver: bridge