apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: sandbox-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: devops-cloudsandbox-auth-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: sandbox-config
                  key: EUREKA_URL