
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
  openapi:
    servers:
      - url: http://localhost:8080
        description: API Gateway

logging:
  level:
    root: INFO
    com.cloudsandbox: DEBUG