server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://postgres-manifest:5432/sandbox_manifest
    username: postgres
    password: adedeji1127
  jpa:
    hibernate:
      ddl-auto: update

sandbox:
  manifest:
    max-file-size: 1MB