server:
  port: ${PORT:8761}

spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html