server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server # This name will now show up in Eureka
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo

# ADD THIS SECTION:
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true