server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
      # Add this to handle failures gracefully
      fail-fast: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka/}
  instance:
    prefer-ip-address: true

# Enable health check
management:
  endpoints:
    web:
      exposure:
        include: health,info